---
title: "Download data"
author: "Laura K Wiley and Stephanie Hicks"
date: "6/14/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r load-libs}
library(here)
library(tidyverse)
library(magrittr)
library(lubridate)
library(DT)
```

Create directories (if needed)
```{r create-dirs}
if(!dir.exists(here("data_processed"))){
  dir.create(here("data_processed"))
}
```

Checks to see if final data object `nih_data.RDS` exists. If not, this code chunk will download the ZIP and CSV files and create one RDS file.

```{r download-raw-data}

if(!file.exists(here("data_processed", "nih_data.RDS"))){
  
  if(!dir.exists(here("data_raw"))){
    dir.create(here("data_raw"))
  }
  
  library(rvest)
  url <- "https://exporter.nih.gov/ExPORTER_Catalog.aspx"
  h <- read_html(url)
  tmp <- h %>%
    html_nodes("td:nth-child(5) div") %>% 
    html_nodes("a") %>% 
    html_attr("href")
  zip_files <- paste0("https://exporter.nih.gov/", tmp)
  rm(h, tmp, url)

  tmp_names <- vector(length = length(zip_files))
  for(i in 1:length(zip_files)){
    tmp_names[i] <- str_split(zip_files[i], "/")[[1]][3]
    download.file(zip_files[i], destfile = here("data_raw", tmp_names[i]), 
                method = "wget")
    unzip(here("data_raw", tmp_names[i]), exdir = here("data_raw"))
    file.remove(here("data_raw", tmp_names[i]))
  }

  csv_files <- list.files(here("data_raw"), ".csv")
  reporter_data <- here("data_raw", csv_files) %>%
    map_dfr(read_csv, col_types = cols(.default = col_character()))

  reporter_data %>% 
    saveRDS(here("data_processed", "nih_data.RDS"))

  unlink(here("data_raw"), recursive = TRUE)
}
```


```{r read-data-in}
reporter_data <- 
    readRDS(file = here("data_processed", "nih_data.RDS"))
```
